### ISSUE TITLE
Add code and descriptions to the simulated datasets  documentation

### ISSUE THREAD

**Issue by ntorresd** [epiverse-trace/serofoi#113]
The datasets `simdata_constant`, `simdata_large_epi` and `simdata_sw_dec` can be generated using the data simulation functions of the package. For instance, the code to generate `simdata_sw_dec` is:
```
no_transm <- 0.0000000001
foi_sim <- c(rep(0.2, 25), rep(0.1, 10), rep(no_transm, 15))

sim_data <- generate_sim_data(foi = foi_sim,
                              sample_size_by_age = 5,
                              tsur = 2050,
                              birth_year_min = 2000,
                              survey_label = 'sw_dec_foi',
                              seed = 1234)
```
We should add this, as well as a brief description of each dataset, to the corresponding R files.

**Comment by ben18785** [comment]
Closing as #160 is going to replace simulated datasets
