### ISSUE TITLE
Pass argument from `fit_seromodel()` to `rstan::sampling()` via `...`

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/serofoi#118]
At the moment, it seems that several arguments are passed from `fit_seromodel()` to `rstan::sampling()` directly, without any transformation.

Additionally, some `rstan::sampling()` are hardcoded, even though users might want to adjust them (e.g., number of chains).

The standard way to deal with this, allowing for maximum flexibility while keeping the `fit_seromodel()` function signature concise and clear, would be to pass argument to `rstan::sampling()` via `...`.

```r
fit_seromodel <- function(
  serodata,
  foi_model,
  decades = 0,
) {
  fit <- rstan::sampling(
    model,
    data = stan_data,
    ...
  )
}
```

Additional reading on `...`: https://adv-r.hadley.nz/functions.html#fun-dot-dot-dot

**Comment by ntorresd** [comment]
@Bisaloo, could you please confirm to me whether this was adequately addressed by #157?

**Comment by Bisaloo** [comment]
Partially, I would also encourage you to simplify the `fit_seromodel()` signature even more to become:

```r
fit_seromodel <- function(
    serodata,
    foi_model = c("constant", "tv_normal_log", "tv_normal"),
    ...
) {
```

However, here are two reasons you may have to keep some argument explicit rather than folding them into `...`:

- if you want to pre-process them or have different actions based on their value, such as suggested in https://github.com/epiverse-trace/serofoi/blob/05ad91238afdc229bd36be272db2d17b09405959/R/modelling.R#L241-L242
- if you **really** want to provide defaults but that already a difficult design choice. For example here, I definitely would add a default for the seed, and would probably rely on `rstan::sampling()` existing defaults for `chains`, `iter`, `thin`, `adapt_delta` and `max_treedepth()`

**Comment by ntorresd** [comment]
The current development version (see #200) already addresses this issue. 

> [...] I would also encourage you to simplify the `fit_seromodel()` signature even more to become:
> 
> ```r
> fit_seromodel <- function(
>     serodata,
>     foi_model = c("constant", "tv_normal_log", "tv_normal"),
>     ...
> ) {
> ```

Besides of the model specification parameters, this is basically how `fit_seromodel()` looks like now:

```r
fit_seromodel <- function(
  serosurvey,
  [model specification parameters],
  ...
)
```

Currently, we are relying on `rstan::sampling` defaults, as you suggested @Bisaloo . We are trying to be very explicit about checking convergence criteria; it's the user's responsability to check whether their results are statistically meaningful or not either using tools provided by the package or other methods proper of Bayesian inference.
