### ISSUE TITLE
prepare_serodata add_age_mean_f = FALSE

### ISSUE THREAD

**Issue by davidsantiagoquevedo** [epiverse-trace/serofoi#121]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [ ] I have the most recent version of linelist and R
 - [X] I have found a bug
 - [X] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------
Hi, I was using the `prepare_serodata()` function setting `add_age_mean_f = FALSE` to avoid grouping the data by `age_mean_f` in the new stan models. In this case, R returns an error message. This occurs because the variable `age_mean_f` is not created, but it is still called out of the `if` sentence in line 60 `dplyr::arrange(.data$age_mean_f)`.

```r
data("veev2012")
veev2012t <- prepare_serodata(veev2012, add_age_mean_f = FALSE)
```

---------

**Comment by ntorresd** [comment]
This will be addressed further by #71.
