### ISSUE TITLE
Github actions builds fails on MacOS and webassembly

### ISSUE THREAD

**Issue by jpavlich** [epiverse-trace/serofoi#131]
R CMD check fails on MacOS both on R-oldrel and R-release
https://github.com/r-universe/epiverse-trace/actions/runs/6801630858/job/18550253451#step:7:891
https://github.com/r-universe/epiverse-trace/actions/runs/6801630858/job/18550253332#step:7:899

Compilation fails for the Webassembly build
https://github.com/r-universe/epiverse-trace/actions/runs/6801630858/job/18550252988#step:4:1369

**Comment by Bisaloo** [comment]
My understanding is that this is fixed by the development version of StanHeaders. However, I don't manage to install StanHeaders from GitHub in #133 so we may have to wait until it's released on CRAN.

**Comment by Bisaloo** [comment]
The failure on macOS seems resolved and as discussed, we expect builds to fail on webassembly at the moment because some system dependencies are unavailable.
