### ISSUE TITLE
Should `plot_()` functions fail when receiving an invalid object?

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/serofoi#136]
At the moment and as far as I can tell, `plot_()` functions will print a message "model did not run" and return an empty plot when receiving an invalid `seromodel_object` (i.e., without samples).

In general, it is recommend to explicitly use `stop()` when the input is invalid rather than a warning and an empty output.

What do you think is the correct behaviour here?

**Comment by ntorresd** [comment]
Returning an empty plot was an early approach we were using from the beginning for this, but I think it would be way cleaner just to use `stop()` when the input is invalid.
