### ISSUE TITLE
refactor prepare_serodata

### ISSUE THREAD

**Issue by zmcucunuba** [epiverse-trace/serofoi#191]
At the moment, `prepare_serodata` only produces `age_mean_f` and adds some columns such as binomial confidence intervals. They could remain. But perhaps we don't need the `sample_size` column, which simply calculates the total sample size and adds that column, which may be misleading. In the short term, we must remove the `sample_size` column.

In the mid-long term, we need `prepare_serodata` to quality-control the data for the user.

**Comment by ben18785** [comment]
A few thoughts:

- We already do checking of the user inputs _within_ the `fit_seromodel` function through `validate_prepared_serodata` function. To me, this means that it's not necessary to force users to go through a pre-fitting quality checking.
- `prepare_serodata` outputs a data frame with lots of columns in it. Only a small subset of these are necessary for fitting the model: `total`, `counts`, `age_mean_f` (I think just renamed `age_middle`) and `tsur` (this only being needed if there are multiple serosurveys).
- The other columns outputted by `prepare_serodata` are useful for plotting.

A proposal:

- `prepare_serodata` is kept but perhaps renamed to `prepare_serodata_for_plotting`. I would suggest modifying it to change column names as per the below.
- For fitting via `fit_seromodel`, we require a user only to supply a data frame with `age_min`, `age_max`, `n_tested`, `n_seropositive` and `year_survey`. We make it clear within the function documentation that we just use the mean of `age_min` and `age_max` for the age when performing inference. This gives us flexibility for the future when we may want to account for the uncertainty in the distribution of ages within the bins when doing inference. This would mean that we would need to change `validate_prepared_serodata` (perhaps renamed as `validate_serodata`) to handle the new inputs.

**Comment by ntorresd** [comment]
As pointed out by @ben18785, the only needed variables for inference are the age group marker `age_group`, `n_seropositive` and `n_sample` (old `sample_size`). From `age_min` and `age_max` we can obtain `age_group` (if not present) using `add_age_group_to_serosurvey()`; this is done both for inference and plotting purposes. This is why from [v1.0.1](https://github.com/epiverse-trace/serofoi/pull/200) we introduced `prepare_serosurvey_for_plotting()`, which only adds the binomial confidence intervals (this function is exported).
