### ISSUE TITLE
Serology data collected in different years and age-dependent FOI

### ISSUE THREAD

**Issue by yungwai-chan** [epiverse-trace/serofoi#56]
Hi all, thanks for developing this useful package. I have a question and a suggestion. 

First I would like to ask about the serology data being imported. The simulated data `simdata_large_epi` is used to illustrate a fast-changing epidemic. It appears to consist of data in one year (2050). I wonder if there is real data available, say before and after an epidemic, or even multiple years' data, would that be suitable to be used in this model (or model 2)?

Also I wonder if estimating age-dependent FOI makes sense, as for some infections there may be considerable difference in FOI by age.

**Comment by ntorresd** [comment]
Hi @yungwai-chan ! thanks for opening up this discussion.

The simulated dataset you refer to is a dataset we simulated to emulate a serological survey collected along a single year (2050) in a population where an epidemic occurred between 2032 and 2035; remember that the serosurvey looks for antibodies in the blood testifying whether individuals were infected at some point in the past. The current version of **serofoi** is restricted to cross-sectional designs meaning that it's not suited for cohort studies or anything involving follow-up. We plan to assess this in the future, but for that there is still a long way to go. As a side note, the functions to simulate datasets are along the way.

Regarding your second question,  we are planing to add in the near future a model allowing for age-dependent FoI along with a suitable use case to showcase its usage (probably an STD), so this is a very relevant topic for us now. I'll leave the issue open so we can further discuss this here later on. 

If you have any further questions or feedback about the package please feel free to reach out to us! It's very important to us to keep in close touch with users in this early stages of development.

**Comment by yungwai-chan** [comment]
Hi @ntorresd, thanks for your response. 

Thanks I do now understand the rationale behind the simulated dataset. What I was thinking was a use case of a human-to-human transmission, that had its prevalence reduced during the covid pandemic. And the cross-sections before and after the pandemic will be different because of the reduced contact. For simplicity perhaps we could just estimate the FOI as 2 separate surveys?

Many thanks for the development of age-dependent FOI, that should be useful to a range of diseases. Will keep an eye on it!
