### ISSUE TITLE
Simulate from time-varying FOI serocatalytic models

### ISSUE THREAD

**Issue by ben18785** [epiverse-trace/serofoi#57]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to simulate from serocatalytic models with known FOIs for power analysis studies.

**Describe the solution you'd like**
Create function(s) to simulate from a range of serocatalytic models.

**Comment by ben18785** [comment]
@ntorresd has this on [this](https://github.com/epiverse-trace/serofoi/tree/dev-simdata) branch

**Comment by ntorresd** [comment]
Hi @ben18785 !

Thanks for opening up this thread, this is a very important discussion for the package moving on. Some functions to simulate data following a particular FoI trend are already available in the [development branch](https://github.com/epiverse-trace/serofoi/tree/dev). 

Positive cases are sampled from a binomial distribution with populations sampled from an exponential distribution although this might change in future versions for the user to be able to choose different PDFs.

**Comment by ben18785** [comment]
Thanks @ntorresd -- does it make sense to make a pull request (for merging it into main) with these code additions?

**Comment by ntorresd** [comment]
Yes! I think is a good time to do this. @GeraldineGomez , @jpavlich what do you think about this? should we update main also in preparation for the summit and in preparation for the full package review @Bisaloo suggested on Slack? I think is important to bare in mind that codecov and the R-CMD-check are not working in the development branch at the time but they show just fine in main.
