### ISSUE TITLE
Modelling workflow

### ISSUE THREAD

**Issue by ben18785** [epiverse-trace/serofoi#61]
At the moment, a user does the following to fit their model:

1. They prepare their data into the format required by the `prepare_serodata` function
2. They run `prepare_serodata` to get data in a form required by the modelling (essentially some additional columns are added to the dataset)
3. They run `run_seromodel` to fit the model.

I'd suggest that users don't really need / want to see `prepare_serodata`, so they'd pass the raw data direct to `run_seromodel`.

**Comment by ben18785** [comment]
Hi @zmcucunuba -- thanks. I agree that users certainly need warnings if their data aren't in the right form. But (sorry, playing Devil's advocate), couldn't that just be done when they do: `run_seromodel`?

Is there another reason a user would want to have the object returned by `prepare_serodata`?

**Comment by zmcucunuba** [comment]
Haha, I guess you're tight @ben18785! Perhaps It's just me being extremely step-by-step-oriented.

**Comment by ekamau** [comment]
Just to add - what is the bare minimum information required for the different models to run, the minimum that should be supplied in the user input data?
Then the functions like `run_seromodel` could indicate that ...
in most instances, one needs at a minimum: age, years of survey, number_seropositive, number_tested. I could be wrong!

But I guess it also depends how much user interaction the workflow requires, or how complex the models are in which case the user gives more information..

**Comment by ntorresd** [comment]
Closed by #200. From v1.0.1 on, the only preprocessing needed for modelling is to add the age group marker `age_group`, which is built from `age_min` and `age_max` whenever it's missing in the survey. See the discussions in #191 and #193 for further details.
