### ISSUE TITLE
Model convergence checking

### ISSUE THREAD

**Issue by ben18785** [epiverse-trace/serofoi#64]
At the moment, we check whether Rhat > 1.1, whereas the current guidelines are Rhat > 1.01.

**Comment by ntorresd** [comment]
Hi @ben18785 !

Do you have any reference I can consult to check this? I'd like to understand the statistical reasons behind this criteria, or is it something arbitrarily defined by the community over time? This is in part just to satisfy my curiosity, hehe.

**Comment by ben18785** [comment]
Yup, see [here](https://arxiv.org/abs/1903.08008).

**Comment by ekamau** [comment]
ESS is always another useful value to check .. it's widely quoted ..

**Comment by ntorresd** [comment]
Closed by #185
