### ISSUE TITLE
Simplify and generalise `get_exposure_ages`

### ISSUE THREAD

**Issue by ben18785** [epiverse-trace/serofoi#70]
As I understand it, `get_exposure_ages` just generates the ages of individuals within a serological sample. At the moment, it does the following:

- determines the minimum birth year in the sample via `min(serodata$birthyear)`
- determines the survey year by looking at the first row of the serodata and subtracting 1
- creates a vector of ages from the minimum birth year to the year before the survey

But what if the data a user supplies does not have samples for all ages? Also, the requirements on the user are somewhat implicit, as the data frame needs to have columns named in a certain way. I'd propose changing this to:

`create_exposure_ages <- function(birthyears, survey_year)`

where `birthyears` is a vector of birth years.

**Comment by ekamau** [comment]
what if the user has data as age and not birth year ... is that step skipped? 
or should the user calculate birth year, externally?
