### ISSUE TITLE
Tidyverse dependency

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/serofoi#82]
The package imports `tidyverse`, which is discouraged:
https://www.tidyverse.org/blog/2018/06/tidyverse-not-for-packages/

It would be good to replace this with the specific packages from the tidyverse that are needed here.

**Comment by jamesmbaazam** [comment]
Related to this, there is need to reduce the number of Imports drastically as it is currently quite dependency heavy. Check this note from `devtools::check()`.

```r
❯ checking package dependencies ... NOTE
  Imports includes 21 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.
```

Related to the [the agreed holistic approach to taking dependencies action item](https://github.com/orgs/epiverse-trace/projects/24/views/2?pane=issue&itemId=33085537), it might be worth thinking about identifying ways to cut down on this. I will keep this in mind as I plan the next steps to achieve this.
