### ISSUE TITLE
Replace custom test functions with equivalents from testthat

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/serofoi#88]
The functions in `tests/testthat/test_utils.R` have equivalents in the [testthat](https://testthat.r-lib.org/articles/custom-expectation.html) package. We should therefore replace the custom functions with those from testthat.

**Comment by ntorresd** [comment]
Outdated. We are restructuring the test infrastructure of the package and increasing test coverage (see https://github.com/epiverse-trace/serofoi/issues/210 and https://github.com/epiverse-trace/serofoi/issues/230 for a summary).
