### ISSUE TITLE
Consider creating an S3 class for objects created by serofoi

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/serofoi#90]
serofoi currently includes some functions to deal with the objects it creates, such as `extract_seromodel_summary()` or `plot_seromodel()`. It would be more idiomatic in R and probably simpler for users to rely of [standard S3 dispatch](https://adv-r.hadley.nz/s3.html) for this.

This way, instead of having to remember the name `extract_seromodel_summary()`, users would just have to type `summary()`, the same way they do when they work with, e.g., `lm` objects.

**Comment by jamesmbaazam** [comment]
I like this idea and would be happy to collaborate on this.

**Comment by ben18785** [comment]
We decided this isn't worth pursuing since we are going to return the raw stanfit objects.
