### ISSUE TITLE
fucntion fit_seromodel( ) and run_seromodel( )

### ISSUE THREAD

**Issue by yungwai-chan** [epiverse-trace/serofoi#95]
I have gone through the references to the [function reference](https://epiverse-trace.github.io/serofoi/reference/index.html) and the two articles. I have also fit the models to my data. Upon checking the output, I am not sure the difference between these two functions (the outputs look fairly similar) and under which condition should I choose a particular one?

**Comment by ntorresd** [comment]
Initially we intended for `run_seromodel` to be like a handler function for `fit_seromodel` allowing for the implementation of the models to multiple serosurveys. At the end we decided to deprecate this function, which will happen in the near future.
