### ISSUE TITLE
Model assumption for constant and changing FOI

### ISSUE THREAD

**Issue by yungwai-chan** [epiverse-trace/serofoi#96]
It is probably a question more than an issue. I have fitted all 3 models with my data for an endemic infection (chickenpox) without intervention (immunisation programme). The fast time-varying foi model fits better than the slow time-varying foi, with the constant foi model having the lowest ELDP. 

Some endemic infection like chickenpox does have cyclical pattern every few years, and certain cohorts may experience higher FOI than the others. But I wonder if the fast time-varying FOI fits best may come from the uncertainty in sampling as well? Often the youngest age group will have the largest sample size and sometimes the older age groups may have varying seroprevalence (not uniformly high), potentially due to sampling issue or smaller sample size. In that case perhaps the time-varying model fit the 'imperfect' data better?

Also it will be great to have option to visualise the prior distribution, especially if this could be customised later.

**Comment by ntorresd** [comment]
Hi @yungwai-chan - I'm very sorry for the very late response to this issue. The package has undergone major updates during the past year, so if this is still something you want to address using the package I recommend you install our current development version (we will release a new version in the following weeks anyway). 

Regarding your question, I think it would be worth taking a look at the serosurveys and see if it makes sense to consider different FOI indexations to address this. If you're still interested, please contact me directly so we can meet and discuss.

I'll move this suggestion to a separate issue:
> Also it will be great to have option to visualise the prior distribution, especially if this could be customised later.
