### ISSUE TITLE
function extract_seromodel_summary()

### ISSUE THREAD

**Issue by yungwai-chan** [epiverse-trace/serofoi#97]
Currently the function summarise the information of the serology survey and the convergence of the model. 

It will be really useful to have the FOI summarised, for instance as median and with 95% confidence bounds.

**Comment by ntorresd** [comment]
You can do this with the current development version of the package by means of `summarise_central_estimate()`:
```r
# constant model
foi_summary <- summarise_central_estimate(
      seromodel = seromodel,
      serosurvey = serosurvey,
      alpha = alpha,
      par_name = "foi",
      central_estimate_digits = central_estimate_digits
    )

# age or time varying models
foi_summary <- summarise_central_estimate(
      seromodel = seromodel,
      serosurvey = serosurvey,
      alpha = alpha,
      par_name = "foi_vector",
      central_estimate_digits = central_estimate_digits
    )
```
You can do this as well for the seroreversion rate in case you use a model that estimates it.
